language: node_js
branches:
  only:
    - master
node_js:
    - "8"
install:
    - npm install
script:
    - npm run compodoc
    - bash ./hack/deploy-gh-pages.sh
env:
  global:
    - GH_REF: github.com/dinivas/dinivas.git

