dinivas:
  production: false
  workspace:
    root-path: '/Users/chidi/.dinivas/workspace'
  terraform:
    debug_command_outputs: false
    state:
      username: dinivas
      password: Pa55w0rd!
    modules:
      - name: project_base
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-project-base.git
      - name: jenkins
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-jenkins.git
      - name: keypair
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-keypair.git
      - name: flavor
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-flavor.git
  keycloak:
    config:
      realm: 'dinivas'
      bearer-only: true
      auth-server-url: 'http://localhost:8085/auth'
      ssl-required: 'external'
      resource: 'dinivas-api'
      verify-token-audience: true
      credentials:
        secret: 'c7629cf6-cd8a-465f-8f08-97af5781bb7f'
      confidential-port: 0
      policy-enforcer:
    admin:
      username: admin
      password: password
