dinivas:
  production: false
  workspace:
    root-path: '/Users/chidi/.dinivas/workspace'
  terraform:
    state:
      username: dinivas
      password: Pa55w0rd!
    modules:
      - name: project_base
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-project-base.git
      - name: keypair
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-keypair.git
  keycloak:
    config:
      realm: 'dinivas'
      bearer-only: true
      auth-server-url: 'http://localhost:8085/auth'
      ssl-required: 'external'
      resource: 'dinivas-api'
      verify-token-audience: true
      credentials:
        secret: 'fca725fb-050b-4332-b432-f34e7078e71c'
      confidential-port: 0
      policy-enforcer:
    admin:
      username: admin
      password: password
