dinivas:
  production: false
  keycloak:
    config:
      realm: 'dinivas'
      bearer-only: true
      auth-server-url: 'http://auth.dinivas.serveo.net/auth'
      ssl-required: 'external'
      resource: 'dinivas-api'
      verify-token-audience: true
      credentials:
        secret: '60de3dca-6c42-42c3-b542-28ca5feb7fc7'
      confidential-port: 0
      policy-enforcer:
    admin:
      username: admin
      password: password
